=== KristjanESPERANTO/MagicMirror-3rd-Party-Modules/dist/schemas/stats.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://magicmirror.builders/schemas/stats.json",
  "title": "Modules Statistics",
  "type": "object",
  "required": [
    "moduleCounter",
    "modulesWithImageCounter",
    "modulesWithIssuesCounter",
    "issueCounter",
    "lastUpdate",
    "repositoryHoster",
    "maintainer"
  ],
  "properties": {
    "moduleCounter": {
      "type": "integer",
      "minimum": 0
    },
    "modulesWithImageCounter": {
      "type": "integer",
      "minimum": 0
    },
    "modulesWithIssuesCounter": {
      "type": "integer",
      "minimum": 0
    },
    "issueCounter": {
      "type": "integer",
      "minimum": 0
    },
    "lastUpdate": {
      "type": "string",
      "format": "date-time"
    },
    "repositoryHoster": {
      "type": "object",
      "minProperties": 1,
      "additionalProperties": false,
      "patternProperties": {
        "^[a-z0-9-]+$": {
          "type": "integer",
          "minimum": 0
        }
      }
    },
    "maintainer": {
      "type": "object",
      "minProperties": 1,
      "additionalProperties": false,
      "patternProperties": {
        "^[A-Za-z0-9_.-]+$": {
          "type": "integer",
          "minimum": 0
        }
      }
    }
  },
  "additionalProperties": false
}

=== KristjanESPERANTO/MagicMirror-3rd-Party-Modules/fixtures/data/stats.json
{
  "moduleCounter": 7,
  "modulesWithImageCounter": 3,
  "modulesWithIssuesCounter": 6,
  "issueCounter": 9,
  "lastUpdate": "2025-09-28T00:00:00.000Z",
  "repositoryHoster": {
    "github": 7
  },
  "maintainer": {
    "CFenner": 1,
    "ItayXD": 1,
    "j-hiller": 1,
    "maxbethge": 1,
    "rubinho101": 1,
    "trumpetx": 1,
    "Unclearogre": 1
  }
}
